def configure(conf):
  pass

def build(bld):
  bld.install_files('${HPREFIX}/util', [
      'value_sort.h',
      ])
  
  bld.shlib(
    source = '',
    vnum = bld.env['VERSION'],
    target = 'pficommon_util')
  
  bld(features = 'cxx cprogram gtest',
      source = 'value_sort_test.cpp',
      target = 'value_sort_test',
      includes = '.')
