def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  bld.install_files('${HPREFIX}/network/rpc', [
      'base.h',
      'exception.h',
      'caller.h',
      'invoker.h',
      'reflect.h',
      ])

  bld.shlib(
    source = 'base.cpp',
    target = 'pficommon_network_rpc',
    includes = '. ..',
    vnum = bld.env['VERSION'],
    use = 'pficommon_network_base pficommon_concurrent pficommon_system')
