def configure(conf):
  pass

def build(bld):
  bld.install_files('${HPREFIX}/text', [
      'xhtml.h',
      'csv.h',
      'json.h',
      'json/base.h',
      'json/parser.h',
      'json/cast.h',
      'json/serialization.h',
      ], relative_trick = True)
  
  bld.shlib(
    source = 'xhtml.cpp csv.cpp json/parser.cpp',
    target = 'pficommon_text',
    includes = '. json',
    vnum = bld.env['VERSION'],
    use = 'pficommon_data pficommon_system')
  
  bld.program(
    features = 'gtest',
    source = 'json_test.cpp json_multiple_definition_test.cpp',
    target = 'json_test',
    includes = '. json',
    use = 'pficommon_text')
  
  bld.program(
    features = 'gtest',
    source = 'csv_test.cpp',
    target = 'csv_test',
    includes = '.',
    use = 'pficommon_text')

  bld.program(
    features = 'gtest',
    source = 'include_test.cpp',
    target = 'include_test',
    includes = '.')
