def build(bld):
  bld.install_files('${HPREFIX}/database/postgresql', [
      'connection.h',
      ])
  
  bld(
    features = bld.env.FEATURES,
    source = 'connection.cpp statement.cpp result.cpp value.cpp',
    target = 'pficommon_database_postgresql',
    install_path = '${PREFIX}/lib',
    includes = '. ..',
    vnum = bld.env['VERSION'],
    use = 'PGSQL')
