def build(bld):
  bld.install_files('${HPREFIX}/database/mysql', [
      'connection.h'
      ])

  bld(
    features = bld.env.FEATURES,
    source = 'connection.cpp statement.cpp value.cpp',
    target = 'pficommon_database_mysql',
    install_path = '${PREFIX}/lib',
    includes = '. ..',
    vnum = bld.env['VERSION'],
    use = 'pficommon_concurrent MYSQL')
