def build(bld):
  bld.install_files('${HPREFIX}/database/mysql', [
      'connection.h'
      ])

  bld.shlib(
    source = 'connection.cpp statement.cpp value.cpp',
    target = 'pficommon_database_mysql',
    includes = '. ..',
    vnum = bld.env['VERSION'],
    use = 'pficommon_concurrent MYSQL')
