
subdirs = [
  'lang',
  'concurrent',
  'network',
  'system',
  'data',
  'database',
  'math',
  'text',
  ]

def options(opt):
  opt.recurse('database')
  opt.recurse('network')

def configure(conf):
  conf.check_cxx(lib = 'pthread')

  conf.recurse(subdirs)

def build(bld):
  bld(
    features = bld.env.FEATURES,
    source = 'empty.cpp',
    target = 'pficommon',
    install_path = '${PREFIX}/lib',
    vnum = bld.env['VERSION'],
    use = [
      'pficommon_concurrent',
      'pficommon_data',
      'pficommon_database',
      'pficommon_lang',
      'pficommon_math',
      'pficommon_network',
      'pficommon_system',
      'pficommon_text',
      ])

  bld.recurse(subdirs)
